before_install:
  - sudo apt-get -y install python-imaging zlib1g-dev libjpeg-dev
  - sudo pip install Pillow
language: python
python:
  - "2.6"
  - "2.7"
install: python setup.py install
script: python unit.py
